Add new package - aide
microsoft/CBL-Mariner pull request #1263
Opened 2021-08-11 16:20 UTC by 0xba1a

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

New package added - aide. It is required for security hardening of Mariner.

###### Change Log  

- Addition of new package aide

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

###### Links to CVEs  

###### Test Methodology

- build package
- build image
- test image in a VM for aide tool functionality

2021-08-11 16:58 UTC, PawelWMS requested changes

2021-08-11 16:58 UTC, PawelWMS commented on SPECS/aide/aide.signatures.json
> +  "aide-0.16.tar.gz": "a81c53a131c4fd130b169b3a26ac35386a2f6e1e014f12807524cc273ed97345",
It looks like you've checked-in an empty tarball. Please remove it.

2021-08-11 16:58 UTC, PawelWMS commented on SPECS/aide/aide.spec
> +- Initial CBL-Mariner import from Fedora 32 (license: MIT)
Please check the package's license and once verified (and potentially updated the `License` tag) indicate that with `License verified` in the changelog.

2021-08-11 17:47 UTC, PawelWMS approved these changes

2021-08-12 02:13 UTC, jslobodzian approved these changes

2021-08-12 04:14 UTC, merged