Removing binaries.
microsoft/CBL-Mariner pull request #1695
Opened 2021-11-30 00:49 UTC by PawelWMS

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [X] The toolchain/worker package manifests are up-to-date
- [X] Any updated packages successfully build (or no packages were changed)
- [X] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [X] All package sources are available
- [X] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [X] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [X] All source files have up-to-date hashes in the `*.signatures.json` files
- [X] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [X] Documentation has been updated to match any changes to the build system
- [X] Ready to merge

---

###### Summary 

I found two binary files with a total size of ~80 MB inside the `SPECS/bond` directory. Moving them to our sources server.

###### Change Log  

- Removed binary files from `SPECS/bond`.

###### Does this affect the toolchain?  

No.

###### Test Methodology

- None, simple file removal.

2021-11-30 13:13 UTC, mfrw requested changes
I double checked if we can build the package, although we have it in the `blobstore`, it complains weirdly for some permission issue:

`time="2021-11-30T18:39:13+05:30" level=debug msg="/bin/sh: /usr/src/mariner/SOURCES/gbc-0.11.0.3-x86_64: Permission denied"`

My hunch is maybe it expected it to `rwx` but when we download it from the blob store, it only remains as `rw`.
Can we please double check once to ensure :)

2021-11-30 22:13 UTC, PawelWMS commented
A great catch, I was not expecting this at all, thank you! I'll fix this in a second.

---
In reply to: [819008367](https://github.com/microsoft/CBL-Mariner/pull/1695#issuecomment-819008367) [](http://example.com/codeflow?ancestors=819008367,819008367)

2021-12-01 03:49 UTC, mfrw approved these changes

2021-12-01 03:49 UTC, mfrw commented on SPECS/bond/bond.spec
> +chmod u+x %{SOURCE1} %{SOURCE2}
LGTM :)

2021-12-01 22:38 UTC, merged