Cameronbaird/CVE 2021 43975
microsoft/CBL-Mariner pull request #1866
Opened 2022-01-08 00:31 UTC by Camelron

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [X] The toolchain/worker package manifests are up-to-date
- [X] Any updated packages successfully build (or no packages were changed)
- [X] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [X] All package sources are available
- [X] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [X] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [X] All source files have up-to-date hashes in the `*.signatures.json` files
- [X] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [X] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
Update kernel to 5.10.88.1 to fix CVE 2021 43975
Add patch for kernel CVE 2021 43976
###### Change Log  

- Update kernel to 5.10.88.1 to fix CVE 2021-43975
- Add patch for kernel CVE 2021-43976

###### Does this affect the toolchain?  

**YES/NO**
YES, kernel-headers
###### Associated issues  

none

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-2021-43975
- https://nvd.nist.gov/vuln/detail/CVE-2021-43976

###### Test Methodology

- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=156466&view=results
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=156882&view=results (still running...)

2022-01-10 17:34 UTC, rlmenge requested changes

2022-01-10 17:34 UTC, rlmenge commented on SPECS/kernel/kernel.spec
> +- Fixes CVE-43975
Please mention both CVEs and create a new line for the patch
- Addressed CVE-2021-43975
- Patch for CVE-2021-43976

2022-01-10 17:34 UTC, rlmenge commented on SPECS/kernel-headers/kernel-headers.spec
> +- Fixes CVE-43975
The Fixes line isn't needed here, just mention why a patch was applied

2022-01-10 17:34 UTC, rlmenge commented on SPECS-SIGNED/kernel-signed/kernel-signed.spec
> +- Fixes CVE-43975
Fixes line not needed

2022-01-10 17:34 UTC, rlmenge commented on SPECS/hyperv-daemons/hyperv-daemons.spec
> +- Fixes CVE-43975
Fixes line not needed , please specify why patch was needed

2022-01-10 17:34 UTC, rlmenge commented on SPECS/hyperv-daemons/hyperv-daemons.spec
> -
Please add newline back just for consistency

2022-01-10 17:34 UTC, rlmenge commented on SPECS/kernel-hyperv/kernel-hyperv.spec
> +- Fixes CVE-43975
same as other comments

2022-01-10 23:05 UTC, christopherco commented on SPECS/kernel/kernel.spec
> +Patch2:         0003-CVE-2021-43976.patch
@nisamson will our patch tooling pick up that CVE-2021-43976 has been patched if we have the `0003-` prefix?

2022-01-10 23:22 UTC, Camelron commented on SPECS/kernel/kernel.spec
> +Patch2:         0003-CVE-2021-43976.patch
Is there a preferred naming convention for CVE patches that actually do something? I.e. not a CVE-2012-12345.nopatch?

2022-01-10 23:31 UTC, Camelron commented
@rlmenge 
The reason CONFIG_I8K is removed in kernel-hyperv/config and not kernel/config is that the update from 78-->88 made I8K depends on CONFIG_HWMON, which is set as a module in kernel but is explicitly unset in kernel-hyperv. 

Similarly, in going from 78-->88 CONFIG_HID_CHICONY and CONFIG_HID_SAMSUNG starts depending on USB_HID. kernel/config has USB_HID=m, kernel-hyperv/config omits USB_HID.

Did some more digging to figure out what config USB_HID is: "Say Y here if you want to connect USB keyboards,
	  mice, joysticks, graphic tablets, or any other HID based devices
	  to your computer via USB, as well as Uninterruptible Power Supply
	  (UPS) and monitor control devices."

2022-01-11 02:42 UTC, rlmenge requested changes

2022-01-11 02:42 UTC, rlmenge commented on SPECS/kernel/CVE-2021-43975.nopatch
> +Upstream: 2c514d25003ac89bb7716bb4402918ccb141f8f5
These are switched
Upstream: b922f622592af76b57cbc566eaeccda0b31a3496
Stable: 2c514d25003ac89bb7716bb4402918ccb141f8f5

2022-01-11 18:47 UTC, Camelron commented on SPECS/kernel/kernel.spec
> +Patch2:         0003-CVE-2021-43976.patch
For now, I'll just drop the 000X- naming convention.

2022-01-12 00:28 UTC, rlmenge approved these changes
:shipit:

2022-01-12 00:33 UTC, rlmenge requested changes

2022-01-12 00:33 UTC, rlmenge commented on SPECS/kernel/kernel.spec
> +- Addressed CVE-2021-43975
Please add new nopatches

2022-01-12 00:38 UTC, rlmenge approved these changes

2022-01-12 00:41 UTC, merged