Update Mariner SPEC files with latest SymCrypt and SCOSSL source
microsoft/CBL-Mariner pull request #2620
Opened 2022-03-30 13:29 UTC by samuel-lee-msft

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Brings in the latest changes to SymCrypt and SCOSSL which include changes required for FIPS certification, and a fix for the build on aarch64.

###### Change Log  
- Update SymCrypt SPEC to consume v101.2.0, which includes changes required for FIPS certification, and a fix for building on Mariner aarch64. Remove ExclusiveArch: x86_64
- Update SymCrypt-OpenSSL SPEC to consume v1.1.0 which include changes required for FIPS certification (invokes SymCrypt with flags to run required self-tests). Remove ExclusiveArch: x86_64, as SymCrypt dependency should now build for aarch64.

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

###### Links to CVEs  

###### Test Methodology

- Local build

2022-03-30 17:26 UTC, PawelWMS commented on SPECS/SymCrypt-OpenSSL/SymCrypt-OpenSSL.spec
> +- Update SymCrypt-OpenSSL to v1.2.0 to include FIPS self-tests, and fix aarch64 build
Typo:
```suggestion
- Update SymCrypt-OpenSSL to v1.1.0 to include FIPS self-tests, and fix aarch64 build
```

2022-03-30 17:27 UTC, PawelWMS approved these changes

2022-03-31 20:53 UTC, Camelron requested changes
We will need to upload the new sources to the blobstore for SymCrypt and Symcrypt-OpenSSL

2022-03-31 21:07 UTC, Camelron approved these changes

2022-03-31 22:57 UTC, merged