Fixing CVE-2020-15705 in `grub2`.
microsoft/CBL-Mariner pull request #319
Opened 2020-10-30 22:41 UTC by PawelWMS

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [X] The toolchain/worker package manifests are up-to-date
- [X] Any updated packages successfully build (or no packages were changed)
- [X] All package sources are available
- [X] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [X] All source files have up-to-date hashes in the `*.signatures.json` files
- [X] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [X] Documentation has been updated to match any changes to the build system
- [X] Ready to merge

---

###### Summary 

Fixing CVE-2020-15705 in `grub2`.

###### Change Log  

- Fixed CVE-2020-15705.

###### Does this affect the toolchain?  

No.

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-2020-15705

###### Test Methodology

Local package build.

2020-11-03 00:29 UTC, dmcilvaney commented
Thoughts on not doing a squash merge here, to keep the CVE fix split from the linter fixes?

2020-11-03 00:29 UTC, dmcilvaney approved these changes

2020-11-03 04:38 UTC, christopherco requested changes
Patching itself looks good. Please also rev the `SPECS-SIGNED/grub2-efi-binary-signed-<x86_64/aarch64>` to keep the version-release aligned

2020-11-04 18:28 UTC, christopherco approved these changes
:shipit:

2020-11-04 18:29 UTC, merged