Bug fix for `ResolveCompetingPackages` when building on RPM-based distro
microsoft/CBL-Mariner pull request #3223
Opened 2022-06-23 18:37 UTC by cwize1

###### Merge Checklist

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary

The current implementation of `ResolveCompetingPackages` assumes it is running on a
distro that doesn't use RPM. Specifically, it doesn't set the root directory which
allows for confusion between the packages being built for CBL-Mariner and the packages
installed on the build system. This change fix this problem by setting the root
directory when calling the `rpm` command.

###### Change Log

- Bug fix for `ResolveCompetingPackages` when building on RPM-based distro

###### Does this affect the toolchain?

NO

###### Test Methodology

- Local build

2022-06-23 18:38 UTC, cwize1 commented
@PawelWMS You may wish to review.

2022-06-23 21:01 UTC, PawelWMS requested changes
I think I don't fully understand this change. The packages are built inside the same environment where `rpm` is called, so the packages installed before we run the fetcher (see: `toolkit/resources/manifests/package/pkggen_core_x86_64.txt` for AMD64) should be taken into account by `rpm`.

2022-06-23 21:23 UTC, cwize1 commented
> I think I don't fully understand this change. The packages are built inside the same environment where `rpm` is called, so the packages installed before we run the fetcher (see: `toolkit/resources/manifests/package/pkggen_core_x86_64.txt` for AMD64) should be taken into account by `rpm`.

The particular call to `rpm` is not being run under a chroot context. So, the `rpm` call uses the system's RPM database, which interferes with the results.

2022-06-23 23:43 UTC, dmcilvaney commented
Yuck, that must have been giving some interesting errors. Should we consider moving this into the fetcher's chroot? We should already have sone stood up by this point (I'm wondering if we may run into macro issues as well).

2022-06-24 17:46 UTC, cwize1 commented
> Yuck, that must have been giving some interesting errors. Should we consider moving this into the fetcher's chroot? We should already have one stood up by this point (I'm wondering if we may run into macro issues as well).

I believe using the `--root` argument on `rpm` is equivalent to using chroot. Also, the `*tmp` directory is the same directory that is used as the fetcher's chroot.

2022-06-24 18:15 UTC, dmcilvaney commented
> > Yuck, that must have been giving some interesting errors. Should we consider moving this into the fetcher's chroot? We should already have one stood up by this point (I'm wondering if we may run into macro issues as well).
> 
> I believe using the `--root` argument on `rpm` is equivalent to using chroot. Also, the `*tmp` directory is the same directory that is used as the fetcher's chroot.

My only concern is the host macros infecting the environment somehow, if that seems to not be the case then go for it.

2022-06-28 23:17 UTC, PawelWMS commented
> > I think I don't fully understand this change. The packages are built inside the same environment where `rpm` is called, so the packages installed before we run the fetcher (see: `toolkit/resources/manifests/package/pkggen_core_x86_64.txt` for AMD64) should be taken into account by `rpm`.
> 
> The particular call to `rpm` is not being run under a chroot context. So, the `rpm` call uses the system's RPM database, which interferes with the results.

Ah, I see what you mean now. Your change makes sense and only one thing bothering me right now, is that we might be missing a reason for why it was setup this way in the first place (might be a bug, might be some quirk of our build system I cannot recall right now). For the sake of making sure nothing breaks, I've started a full end-to-end build for this change (build ID: 207574). If that's going to be green, we can go ahead and merge.

2022-06-29 17:45 UTC, PawelWMS approved these changes
Unblocking, looks like all package builds (at least the core ones) are passing.

2022-06-30 22:08 UTC, cwize1 commented
What are the next steps to getting this merged?

2022-07-05 22:21 UTC, oliviacrain approved these changes

2022-07-05 22:21 UTC, merged