Update ceph to v16.2.10 to address CVE-2022-0670
microsoft/CBL-Mariner pull request #3497
Opened 2022-08-05 22:01 UTC by Camelron

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

###### Change Log  

- Change
- Change
- Change

###### Does this affect the toolchain?  

**YES/NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2022-08-06 22:04 UTC, PawelWMS commented on SPECS/ceph/ceph.signatures.json
> +  "ceph-16.2.10.tar.gz": "df8dbe9d45779825fb4097d94a72847e7405089c0999541e62779f2705bf02d5"
Why 16.2.10 and not 17.2.2? [NIST](https://nvd.nist.gov/vuln/detail/CVE-2022-0670#range-8182707) seems to suggest that's the first version with this CVE patched.

2022-08-07 04:45 UTC, mfrw reviewed
For what it's worth; it seems, we might have a build-break.

I got an error:

`install: cannot stat 'sudoers.d/ceph-osd-smartctl': No such file or directory"`

Maybe we should double check.

2022-08-08 20:35 UTC, Camelron commented on SPECS/ceph/ceph.signatures.json
> +  "ceph-16.2.10.tar.gz": "df8dbe9d45779825fb4097d94a72847e7405089c0999541e62779f2705bf02d5"
For our major version (Pacific, 16.X.X), 16.2.10 is the version with the fix. See here https://docs.ceph.com/en/latest/security/CVE-2022-0670/

2022-08-08 23:52 UTC, PawelWMS commented on SPECS/ceph/ceph.signatures.json
> +  "ceph-16.2.10.tar.gz": "df8dbe9d45779825fb4097d94a72847e7405089c0999541e62779f2705bf02d5"
Amazing, thank you! In that case please also send NIST an e-mail, so they'd update their database to include 16.2.10 as a fixed version. It's the polite thing to do and also without it our tooling will keep complaining about `ceph`.;)

2022-08-08 23:53 UTC, PawelWMS approved these changes
Just one request to send an e-mail to NIST but that's outside the scope of this PR.

2022-08-09 03:10 UTC, mfrw requested changes
Blocking the PR:
I've got one more build break:
`cp: cannot stat 'monitoring/grafana/README.md': No such file or directory`

2022-08-10 03:00 UTC, mfrw approved these changes
LGTM :)
Thanks for addressing the comments.

2022-08-10 17:50 UTC, merged

2022-08-10 18:11 UTC, Camelron commented on SPECS/ceph/ceph.signatures.json
> +  "ceph-16.2.10.tar.gz": "df8dbe9d45779825fb4097d94a72847e7405089c0999541e62779f2705bf02d5"
email is sent