[dev] Python 3: Upgrade to fix CVE-2019-20907, CVE-2020-26116, CVE-2019-18348, CVE-2020-14422, Patch CVE-2020-27619
microsoft/CBL-Mariner pull request #361
Opened 2020-11-10 21:43 UTC by thcrain-msft

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Upgrades python3 package to 3.7.9 to fix several CVEs. Separately patches CVE-2020-27619

###### Change Log  

- Upgrade Python3 to 3.7.9 to fix several CVEs listed in title
- Additionally, patches CVE-2020-27619

###### Does this affect the toolchain?  

NO

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-2020-27619
- https://nvd.nist.gov/vuln/detail/CVE-2019-20907
- https://nvd.nist.gov/vuln/detail/CVE-2020-26116
- https://nvd.nist.gov/vuln/detail/CVE-2019-18348
- https://nvd.nist.gov/vuln/detail/CVE-2020-14422

###### Test Methodology

- Currently building package locally

2020-11-11 19:35 UTC, schmittjoseph requested changes

2020-11-11 19:35 UTC, schmittjoseph commented on SPECS/python3/python3.spec
> +%if %{with_check}
The `check` changes should not be added to `dev`. In their current state  neither `iana-etc` nor `tzdata` is part of the toolchain yet is a br of a toolchain package. This will result in a build break for dev

2020-11-11 19:35 UTC, schmittjoseph commented on SPECS/python3/python3.spec
> +make  %{?_smp_mflags} test
See above comment, this `check` change should be reverted.

2020-11-12 18:33 UTC, thcrain-msft commented
Closing- miscommunication, we don't need to pull this into dev just yet

2020-11-12 18:33 UTC, closed without merging