Add portmap to rpcbind provides
microsoft/CBL-Mariner pull request #3709
Opened 2022-09-07 21:29 UTC by MateuszMalisz

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Add portmap as an explicit `Provides` to enable build of some packages.

###### Change Log  

- Add `portmap` to rpcbind `Provides`

###### Does this affect the toolchain?  

**NO**

###### Test Methodology

- Pipeline buddy build

2022-09-07 21:55 UTC, oliviacrain requested changes
Change itself looks good, but please retarget against the `main` branch

2022-09-07 21:55 UTC, oliviacrain commented on SPECS/rpcbind/rpcbind.spec
> +- Add portman to provides
```suggestion
- Add portmap to provides
```

2022-09-07 22:06 UTC, MateuszMalisz commented on SPECS/rpcbind/rpcbind.spec
> +- Add portman to provides
Good catch!

2022-09-07 22:13 UTC, oliviacrain approved these changes
🚀

2022-09-08 23:06 UTC, jslobodzian approved these changes

2022-09-16 23:04 UTC, merged