Update grub command line with inst.stage2 label CDROM
microsoft/CBL-Mariner pull request #384
Opened 2020-11-16 08:08 UTC by chalamalasetty

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

###### Change Log  

- Change
- Change
- Change

###### Does this affect the toolchain?  

**YES**
NO

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/...

###### Test Methodology

- Pipeline build id: xxxx

2020-11-16 17:34 UTC, christopherco requested changes
I don't quite understand this change yet. `inst.stage2` appears to be an anaconda-specific setting (https://anaconda-installer.readthedocs.io/en/latest/boot-options.html#inst-stage2) and Mariner doesn't use the anaconda installer. Please explain why `inst.stage2` is required here.

2020-11-17 00:37 UTC, chalamalasetty commented
I am not sure why it is only working when I use this flag "inst.stage2". I am using rufus tool to laydown ISO to USB and not sure if rufus is doing something here. will look into it further,

2020-11-23 01:14 UTC, chalamalasetty commented
The use of mariner.media=CDROM is a workaround that our installer does not require, but is observed to be needed to boot on some hardware/SoCs.

2020-11-23 01:46 UTC, christopherco approved these changes

2020-11-23 19:13 UTC, PawelWMS approved these changes

2020-11-23 21:10 UTC, anphel31 approved these changes

2020-11-23 23:27 UTC, merged