fix CVE-2021-3995
microsoft/CBL-Mariner pull request #3930
Opened 2022-10-06 10:29 UTC by 0xba1a

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Upgrade util-linux package to version 2.37.4

###### Change Log  

- Upgrade util-linux package to version 2.37.4
- Build util-linux without audit (older version also didn't have audit support)
- Avoid CVE-2021-3995 which was found in older version

###### Does this affect the toolchain?  

**YES**

###### Associated issues  

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-2021-3995

###### Test Methodology

- Local package build

2022-10-06 10:32 UTC, 0xba1a commented
BuddyBuild

- AMD64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=247081&view=results
- ARM64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=247082&view=results

Complete build
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=247083&view=results

2022-10-07 05:21 UTC, 0xba1a commented on SPECS/util-linux/util-linux.spec
> -Version:        2.32.1
All the versions upto 2.37.3 are vulnerable
![image](https://user-images.githubusercontent.com/2942888/194473435-45eef270-c06a-410d-ab16-dc55a3202e9c.png)

2022-10-07 06:30 UTC, 0xba1a commented on SPECS/util-linux/util-linux.spec
> +Conflicts:      shadow-utils < 4.9-10
I took util-linux form the `main` branch.  For 2.0 `su` tool is provided by `util-linux`. But in 1.0 it is provided by `shadow-utils`.

To maintain the same, let me remove `su` from `util-linux` and remove the conflict as well.

2022-10-07 14:57 UTC, oliviacrain commented on SPECS/util-linux/util-linux.spec
> -Version:        2.32.1
Are we not able to backport the patch?

2022-10-07 15:02 UTC, oliviacrain commented on SPECS/util-linux/util-linux.spec
> -Version:        2.32.1
Also, we should try to exploit this vulnerability ourselves, to see if NVD's data is correct. [Ubuntu is saying](https://ubuntu.com/security/CVE-2021-3995) that this was introduced in v2.34.

2022-10-07 15:05 UTC, oliviacrain requested changes
Blocking- would like confirmation that we're actually vulnerable to this bug, please see above comment.

2022-10-07 19:08 UTC, jslobodzian requested changes
The buddy build failed.  We should backport the change.  I think this is too large/risky for Mariner 1.0 at the moment.

2022-10-12 03:00 UTC, 0xba1a commented on SPECS/util-linux/util-linux.spec
> -Version:        2.32.1
@oliviacrain I tried applying the patch first. It's not applying. Some functions are not yet implemented in the older version. So manually updating the patch will not be a good idea.

Let me explore the seriousness of the vulnerability.

2022-10-12 16:56 UTC, oliviacrain commented on SPECS/util-linux/util-linux.spec
> -Version:        2.32.1
I looked at the [initial posting of the vuln to openwall](https://www.openwall.com/lists/oss-security/2022/01/24/2). It lists the below commit as the initial introduction of the vulnerability.

https://github.com/util-linux/util-linux/commit/5fea669e9ef0a08804f72bb40f859f239f68c30a

This commit is introduced in v2.34, and we're on v2.32 here, so I think we can safely close this PR. We do need to ask NIST to correct the NVD database, though.

2022-10-12 17:38 UTC, neha170 commented on SPECS/util-linux/util-linux.spec
> -Version:        2.32.1
I had reached the same conclusion wrt when the vulnerability was introduced, and had sent a mail to NIST. Awaiting reply, closing this PR.

2022-10-12 17:40 UTC, neha170 commented
Closing this PR. Our version shouldn't be affected by this, as the offending code was introduced in a later version. Awaiting reply from NIST.

2022-10-12 17:40 UTC, closed without merging