Let openldap depend on cyrus-sasl
microsoft/CBL-Mariner pull request #4767
Opened 2023-02-04 05:34 UTC by snambakam

* Let openldap depend on cyrus-sasl-bootstrap instead of cyrus-sasl in order to avoid a circular dependency.

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Build openldap with cyrus-sasl support

###### Change Log  

Build openldap with cyrus-sasl support.
Let openldap depend on cyrus-sasl-bootstrap in order to avoid cyclic dependency

###### Does this affect the toolchain?  
NO

###### Test Methodology
local build

2023-02-10 18:58 UTC, anphel31 commented
Can you please update ../SPECS/LICENSES-AND-NOTICES/data/licenses.json (as mentioned in the license map check)

2023-02-10 19:06 UTC, anphel31 approved these changes

2023-02-10 19:14 UTC, PawelWMS commented on SPECS/cyrus-sasl/cyrus-sasl.spec
> +Release:        2%{?dist}
Please also add a changelog entry.

2023-02-10 19:15 UTC, PawelWMS commented on SPECS/openldap/openldap.spec
> +BuildRequires:  cyrus-sasl-bootstrap-devel >= 2.1
Please also increment the `Release` tag and add changelog entry.

2023-02-10 19:19 UTC, PawelWMS commented on SPECS/openldap/openldap.spec
> +Requires:       cyrus-sasl-bootstrap-lib >= 2.1
This should not be required and in fact I would either remove it (both the regular and bootstrap version will provide the required libraries and RPM is smart enough to depend on libraries and not package names), or change it `cyrus-sasl-lib`. Otherwise, we're making it seem like the bootstrap version is actually needed during run-time. Also, if we ever decide to stop publishing bootstrap packages, this might then break.

2023-02-10 19:20 UTC, PawelWMS requested changes
Just a few more tweaks, but looks good!

2023-02-13 22:37 UTC, PawelWMS approved these changes

2023-02-13 22:38 UTC, merged