Patch e2fsprogs CVE-2019-5094, CVE-2019-5188
microsoft/CBL-Mariner pull request #535
Opened 2021-01-13 19:02 UTC by dmcilvaney

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/tools/cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Patch CVE-2019-5094 and CVE-2019-5188 for `e2fsprogs` package in the 1.0 branch.

###### Change Log  

- fix CVE-2019-5094
- fix CVE-2019-5188

###### Does this affect the toolchain?  

**YES**

###### Links to CVEs  
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5094
- https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-5188

###### Test Methodology
- Pipeline build id: 59147

2021-01-13 19:03 UTC, dmcilvaney commented
Local build failed due to power outage, so I'm running a pipeline build.

2021-01-19 16:42 UTC, jslobodzian requested changes

2021-01-19 16:42 UTC, jslobodzian commented on SPECS/e2fsprogs/e2fsprogs.spec
> +- Address CVE-2019-5094
and CVE 2019-5188

2021-01-19 20:13 UTC, jslobodzian approved these changes

2021-01-19 22:19 UTC, hbeberman approved these changes

2021-01-19 22:19 UTC, merged