fix: Enable lzo, snappy, zstd support in crash
microsoft/CBL-Mariner pull request #6380
Opened 2023-10-10 07:43 UTC by christopherco

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Issue discovered in crash where lzo compressed kdump files were not
readable by our crash utility. So add a patch to enable support for
common compression types (lzo, snappy, zstd)

Signed-off-by: Chris Co <chrco@microsoft.com>

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- https://microsoft.visualstudio.com/OS/_workitems/edit/43839616

###### Test Methodology

- Pipeline build id:

2023-10-19 08:32 UTC, christopherco commented on SPECS/crash/lzo_snappy_zstd.patch
> +--- crash-8.0.1/Makefile.orig
Patch file comes from https://src.fedoraproject.org/rpms/crash/blob/rawhide/f/lzo_snappy_zstd.patch

2023-10-23 18:34 UTC, ddstreetmicrosoft approved these changes
LGTM

2023-10-23 21:29 UTC, Camelron requested changes
My build breaks;

unable to hydrate file: lzo_snappy_zstd.patch

We forgot to update signature.json


---Nevermind, I just cherry-picked the changes in a messy/wrong way and it caused a false alarm. PatchX files are not part of the signature.json..

2023-10-23 21:53 UTC, Camelron approved these changes

2023-10-24 08:09 UTC, merged