Backport 30 patches to bring grub 2.06 up to SBAT level 2
microsoft/CBL-Mariner pull request #6469
Opened 2023-10-18 18:43 UTC by gjswalling

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

In order to update grub SBAT level 1->2, backported and applied 30 upstream patches:
https://www.openwall.com/lists/oss-security/2022/06/07/5

###### Change Log  

- grub 2.06 CVE-2021-3695 CVE-2021-3696 CVE-2021-3697 CVE-2022-28733 CVE-2022-28734
  CVE-2022-28735 CVE-2022-28736

###### Does this affect the toolchain?  

NO

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-2021-3695
- https://nvd.nist.gov/vuln/detail/CVE-2021-3696
- https://nvd.nist.gov/vuln/detail/CVE-2021-3697
- https://nvd.nist.gov/vuln/detail/CVE-2022-28733
- https://nvd.nist.gov/vuln/detail/CVE-2022-28734
- https://nvd.nist.gov/vuln/detail/CVE-2022-28735
- https://nvd.nist.gov/vuln/detail/CVE-2022-28736

###### Test Methodology

- local build and manually booted the following scenarios:
results                                                       expected actual 
------------------------------------------------------------ 
sb enabled + shim + grub + Mariner 2.0  success success 
sb disabled + shim + grub + Mariner 2.0 success success 
sb enabled + grub + Mariner 2.0             fail fail 
sb disabled + grub + Mariner 2.0            success success

2023-10-24 21:44 UTC, Camelron approved these changes
lgtm. I installed this during our kata image pipeline and validated that that image passed e2es. I also deployed the resulting image, verified the binary checksums match, and that everything else in the cluster looks normal. 

EDIT- seems e2es falsely report success when it decides to run no tests. E2Es did not actually run!

2023-10-24 21:59 UTC, Camelron requested changes
Hold on, my AgentBaker broke the image I was validating with. Will rerun the pipeline.

2023-10-25 00:03 UTC, Camelron approved these changes
LGTM, see latest pipeline run https://dev.azure.com/mariner-org/mariner/_build/results?buildId=440860&view=results

2023-10-26 08:33 UTC, christopherco approved these changes

2023-10-26 19:45 UTC, merged