Upgrade kernel to 5.15.136.1 and add AMDGPU support
microsoft/CBL-Mariner pull request #6614
Opened 2023-10-27 16:36 UTC by rlmenge

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Upgrade kernel to 5.15.136.1 and add AMDGPU support

This upgrade includes an additional feature branch for the AMDGPU drivers. This has led to additional config changes to enable.

###### Change Log  

- Upgrade to 5.15.136.1

###### Does this affect the toolchain?  

**YES**

###### Test Methodology

- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=441955&view=results

2023-10-27 18:42 UTC, neha170 reviewed
Just wondering why the auto upgrade pipeline was not able to handle this, thanks

2023-10-27 19:23 UTC, rlmenge commented
> Just wondering why the auto upgrade pipeline was not able to handle this, thanks

The orignal autopatcher [PR](https://github.com/microsoft/CBL-Mariner/pull/6593) was failing with build errors and differing configs. I wanted to preserve this data for historical and debugging purposes but I also had to rebase. Therefore I made a new PR :) . Also updated the description with this

2023-10-27 19:28 UTC, henryli001 reviewed
Just would like to clarify what "AMDGPU support" refers to here? 

I looked at the related kernel configs and it seems that the configs that are responsible for building the drivers such as DRM_AMDGPU, DRM_AMDGPU_SI and DRM_AMDGPU_CIK have already been enabled. So does it mean that the kernel is already capable of building the drivers and this PR adds additional support for AMD GPU like enabling display engine config? (Please correct me if I'm wrong here).

2023-10-27 21:11 UTC, rlmenge commented
> Just would like to clarify what "AMDGPU support" refers to here?
> 
> I looked at the related kernel configs and it seems that the configs that are responsible for building the drivers such as DRM_AMDGPU, DRM_AMDGPU_SI and DRM_AMDGPU_CIK have already been enabled. So does it mean that the kernel is already capable of building the drivers and this PR adds additional support for AMD GPU like enabling display engine config? (Please correct me if I'm wrong here).

It is a completely new feature branch merged in. The code is not fully upstream yet which is why I called it out. The config changes are a reflection of the new code being added to the kernel :) 

You can see this change by looking at the [commit ](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/commit/d9d3c62870abf05849104bfce24935be520b1e19)for the kernel source or the [merge file](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/blob/rolling-lts/mariner-2/5.15.136.1/MSFT-Merge/log) for the source here 

I have also updated the description with this

2023-10-28 01:37 UTC, rlmenge commented
kernel-hci and kernel-azure are not building as expected. Need to analyze their configs before this merges

2023-10-30 23:44 UTC, Camelron commented on SPECS-SIGNED/kernel-azure-signed/kernel-azure-signed.spec
> -* Tue Sep 22 2023 Cameron Baird <cameronbaird@microsoft.com> - 5.15.131.1-3
sorry about that...

2023-10-30 23:54 UTC, Camelron approved these changes
lgtm

2023-10-31 00:34 UTC, christopherco requested changes

2023-10-31 01:26 UTC, rlmenge commented on SPECS/kernel/kernel.spec
> +BuildRequires:  cpio
done :)

2023-10-31 01:52 UTC, rlmenge commented on SPECS/kernel-hci/kernel-hci.spec
> +Version:        5.15.136.1
Wait on merging until kernel-hci validation from @vinceaperri has passed

2023-11-06 18:31 UTC, rlmenge commented
Looking to add AMDGPU drivers in a seperate kernel. Closing this PR

2023-11-06 18:31 UTC, closed without merging