Nopatch kernel CVE-2023-2430, CVE-2023-3338, CVE-2023-39191, CVE-2023-42752 ...
microsoft/CBL-Mariner pull request #6651
Opened 2023-11-01 22:28 UTC by Camelron

…for kernel

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

###### Change Log  

- CVE-2023-2430.nopatch
- CVE-2023-3338.nopatch
- CVE-2023-39191.nopatch
- CVE-2023-42752.nopatch

###### Does this affect the toolchain?  

**YES/NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-2023-2430
- https://nvd.nist.gov/vuln/detail/CVE-2023-3338
- https://nvd.nist.gov/vuln/detail/CVE-2023-39191
- https://nvd.nist.gov/vuln/detail/CVE-2023-42752

###### Test Methodology

- Pipeline build id: xxxx

2023-11-01 22:34 UTC, Camelron commented on SPECS/kernel/CVE-2023-39191.nopatch
> +Since we set sysctl.kernel.unprivileged_bpf_disabled=1 for all of our images,
@ddstreetmicrosoft Do you mind vetting the logic here? https://nvd.nist.gov/vuln/detail/CVE-2023-39191

1. the CVE may allow an attacker with CAP_BPF privileges to escalate privileges and execute arbitrary code in the context of the kernel
2. In all cases, we ship unprivileged_bpf_disabled=1 meaning users without CAP_SYS_ADMIN can't load ebpf programs
3. Thus, there is no danger of privilege escalation, one needs to be admin already to abuse this. Admin is not part of our thread model. 

Are any of my assumptions wrong?

2023-11-02 00:02 UTC, rlmenge commented on SPECS/kernel/CVE-2023-2430.nopatch
> +But io_uring.c isn't introduced until 36404b09aa609e00f8f0108356830c22b99b3cbf; not backported to 5.15.*
Nit: I think you mean msg_ring.c isn't introduced until

2023-11-02 18:22 UTC, Camelron commented on SPECS/kernel/CVE-2023-2430.nopatch
> +But io_uring.c isn't introduced until 36404b09aa609e00f8f0108356830c22b99b3cbf; not backported to 5.15.*
absolutely, thanks!

2023-11-03 08:14 UTC, christopherco requested changes

2023-11-03 08:14 UTC, christopherco commented on SPECS/kernel/CVE-2023-39191.nopatch
> +Since we set sysctl.kernel.unprivileged_bpf_disabled=1 for all of our images,
Are you sure we are actually affected by this CVE? From my investigation, it looks like this vulnerability is in the dynptr feature of BPF which is a newer feature and I do not see in the 5.15 stable trees.

2023-11-03 12:28 UTC, ddstreetmicrosoft commented on SPECS/kernel/CVE-2023-39191.nopatch
> +Since we set sysctl.kernel.unprivileged_bpf_disabled=1 for all of our images,
> In all cases, we ship unprivileged_bpf_disabled=1

This is only our default boot cmdline though; in general, we should still fix bugs even if our default cmdline settings would mitigate the issue, as end users could remove this cmdline setting.

But for this particular case, I think @christopherco is correct that it doesn't affect our older kernel because the dynptr feature that introduced the bug was added later (it looks like around 5.19 I think)

2023-11-06 17:37 UTC, christopherco approved these changes

2023-11-06 17:43 UTC, Camelron commented on SPECS/kernel/CVE-2023-39191.nopatch
> +Since we set sysctl.kernel.unprivileged_bpf_disabled=1 for all of our images,
This reasoning makes sense, thanks! 

I have independently verified that the introducing commit is not present in the 5.15 tree https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.137&id=97e03f521050c092919591e668107b3d69c5f426

The changes to add dynptrs are indeed not present, for example, in the header file: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/linux/bpf.h?h=v5.15.137

2023-11-06 18:05 UTC, merged